###
GET http://localhost:8000/api/health_check
###
GET http://localhost:8000/api/books
###
GET http://localhost:8000/api/loans
###
POST http://localhost:8000/api/loans
Content-Type: application/json
Authorization: Bearer hogehoge

{
  "book_id": "12BD8E30-8F33-4B46-88E6-DD88B70EE6E2",
}
###
Put http://localhost:8000/api/loans
Content-Type: application/json
Authorization: Bearer hogehoge

{
  "book_id": "64727F60-DFCD-4776-826D-C9FFFD334A3A",
}
