###
GET http://localhost:8000/api/health_check
###
GET http://localhost:8000/api/books
###
GET http://localhost:8000/api/loans
###
POST http://localhost:8000/api/loans
Content-Type: application/json
Authorization: Bearer hogehoge

{
  "book_id": "6D46233F-02A7-4851-ADBF-527ECD6E3F53",
}
