[tools]
erlang = "latest"
gleam = "latest"
node = "latest"
rebar = "latest"

[tasks.serve]
run = """
  watchexec --restart --clear --wrap-process=session --stop-signal \
  SIGTERM --exts gleam --watch src/ -- "gleam run"
"""
description = "run the CLI"

[tasks.migrate]
run = """
  rm -f database.sqlite3
  atlas migrate apply --env dev
"""
description = "Apply database migrations using Atlas"

[tasks.schema]
run = """
  atlas schema inspect -u "sqlite://database.sqlite3" --format '{{ json . }}'
"""
description = "Apply database migrations using Atlas"
