openapi: 3.0.3
info:
  title: Helpdesk API
  version: 1.0.0
  description: Basic ticket support system API

paths:
  /tickets:
    get:
      summary: Get all tickets
      responses:
        "200":
          description: List of tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ticket"

    post:
      summary: Create a new ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTicket"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ticket"

  /tickets/{id}:
    get:
      summary: Get a specific ticket
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Ticket found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ticket"
        "404":
          description: Not found

    patch:
      summary: Update ticket status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateStatus"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ticket"

  /tickets/{id}/responses:
    post:
      summary: Add a response to a ticket
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewResponse"
      responses:
        "201":
          description: Response added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"

components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          $ref: "#/components/schemas/TicketStatus"
        created_at:
          type: string
          format: date-time
        responses:
          type: array
          items:
            $ref: "#/components/schemas/Response"

    NewTicket:
      type: object
      required: [title, description]
      properties:
        title:
          type: string
        description:
          type: string

    UpdateStatus:
      type: object
      required: [status]
      properties:
        status:
          $ref: "#/components/schemas/TicketStatus"

    TicketStatus:
      type: string
      enum:
        - Open
        - InProgress
        - Closed

    NewResponse:
      type: object
      required: [author, content]
      properties:
        author:
          type: string
        content:
          type: string

    Response:
      type: object
      properties:
        author:
          type: string
        content:
          type: string
        timestamp:
          type: string
          format: date-time
