curl -X GET http://127.0.0.1:8000
###
curl -X GET http://127.0.0.1:8000/persons/
###
curl -X GET http://127.0.0.1:8000/tickets/
###
curl -X GET http://127.0.0.1:8000/tickets/?status=close
###
curl -X GET http://127.0.0.1:8000/tickets/?status=hoge
